sudo: required

language: haskell

services:
  - docker

before_install:
  - docker build -t agussell/detexify-hs-backend .
  - docker run --rm --name detexify -p 3000:3000 -t agussell/detexify-hs-backend

cache:
  directories:
  - .
